name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: gocache
      run: go build -v ./gocache.go

    - name: client
      run: go build -v -o client_ ./cmd/client.go

    - name: simulator
      run: go build -v ./cmd/simulator.go

    - name: iperf
      run: go build -v ./cmd/iperf.go

    - name: Test
      run: go test -v .
